"$schema" = 'https://starship.rs/config-schema.json'

palette = "catppuccin_mocha"

format = """
\
$os\
$username\
[](bg:#9063CD fg:#307FE2)\
$directory\
[](fg:#9063CD bg:#FFB900)\
$git_branch\
$git_status\
[](fg:#FFB900 bg:#3CB17E)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:#3CB17E bg:#DA291C)\
$docker_context\
[](fg:#DA291C bg:#2CCCD3)\
$time\
[ ](fg:#2CCCD3)
$character"""

# Add a blank line between prompts
add_newline = true

[username]
show_always = true
style_user = "bg:#307FE2 fg:#ffffff"
style_root = "bg:#307FE2 fg:#ffffff"
format = '[ $user ]($style)'
disabled = false

[os]
style = "bg:#307FE2 fg:#ffffff"
disabled = true

[directory]
style = "bg:#9063CD fg:#ffffff"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[c]
symbol = " "
style = "bg:#3CB17E fg:#ffffff"
format = '[ $symbol($version) ]($style)'

[cpp]
symbol = " "
style = "bg:#3CB17E fg:#ffffff"
format = '[ $symbol($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#DA291C fg:#ffffff"
format = '[ $symbol$context ]($style)'

[elixir]
symbol = " "
style = "bg:#3CB17E fg:#ffffff"
format = '[ $symbol($version) ]($style)'

[elm]
symbol = " "
style = "bg:#3CB17E fg:#ffffff"
format = '[ $symbol($version) ]($style)'

[git_branch]
symbol = ""
style = "fg:#ffffff bg:#FFB900"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "fg:#ffffff bg:#FFB900"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#3CB17E fg:#ffffff"
format = '[ $symbol($version) ]($style)'

[gradle]
style = "bg:#3CB17E fg:#ffffff"
format = '[ $symbol($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#3CB17E fg:#ffffff"
format = '[ $symbol($version) ]($style)'

[java]
symbol = " "
style = "bg:#3CB17E fg:#ffffff"
format = '[ $symbol($version) ]($style)'

[julia]
symbol = " "
style = "bg:#3CB17E fg:#ffffff"
format = '[ $symbol($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#3CB17E fg:#ffffff"
format = '[ $symbol($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:#3CB17E fg:#ffffff"
format = '[ $symbol($version) ]($style)'

[rust]
symbol = ""
style = "bg:#3CB17E fg:#ffffff"
format = '[ $symbol($version) ]($style)'

[scala]
symbol = " "
style = "bg:#3CB17E fg:#ffffff"
format = '[ $symbol($version) ]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:#2CCCD3 fg:#1a1a1a"
format = '[  $time ]($style)'

[character]
success_symbol = '[→](bold green)'
error_symbol = '[✗](bold red)'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
